name: Deploy Client
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: MyDay.Client
    steps:
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            MyDay.Client:
              - 'MyDay.Client/**'

      - name: Running the container

        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t aniruddocyard/myday-client -f Dockerfile.dev .
          docker run -e CI=true aniruddocyard/myday-client npm run test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to ElasticBeanStalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: myday
          environment_name: Myday-env
          existing_bucket_name: elasticbeanstalk-us-west-2-901468922895
          region: us-west-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
