name: GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - "MyDay-Client/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          cd MyDay-Client
          npm install

      - name: Build
        run: |
          cd MyDay-Client 
          npm run build

      - name: Deploy
        if: success()
        run: aws s3 sync ./MyDay-Client/dist/mydayclient s3://com.myd4y
