name: Deploy Client
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      # - name: Running the container
      #   run: |
      #     docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      #     docker build -t aniruddocyard/myday-client -f ./MyDay-Client/Dockerfile.dev ./MyDay-Client

      # - name: Generate deployment package
      #   run: |
      #     zip -r deploy.zip ./MyDay-Client -x '*.git*' -x '**node_modules'
      #     cd ./MyDay-Client && ls

      # - name: Deploy to ElasticBeanStalk
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: myday
      #     environment_name: Myday-env
      #     existing_bucket_name: elasticbeanstalk-us-west-2-901468922895
      #     region: us-west-2
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip
