name: Deploy Client
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - uses: dorny/paths-filter@v2
      #   id: filter
      #   with:
      #     filters: |
      #       MyDay.Client:
      #         - 'MyDay.Client/**'
      - name: Running the container
        working-directory: MyDay.Client
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t aniruddocyard/myday-client .
      - name: Generate deployment package
        working-directory: MyDay.Client
        run: |
          zip -r deploy.zip . -x '*.git*'

      - name: Deploy to ElasticBeanStalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: myday
          environment_name: Myday-env-1
          existing_bucket_name: elasticbeanstalk-us-west-2-901468922895
          use_existing_version_if_available: true
          region: us-west-2
          version_label: ${{ github.sha }}
          deployment_package: MyDay.Client/deploy.zip
